# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



target 'SmartUnify' do
  # Comment the next line if you don't want to use dynamic frameworks
  

  # Pods for SmartUnify
  
  pod 'LDVLib01', :path => '../LDVLib01'

  target 'SmartUnifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartUnifyUITests' do
    # Pods for testing
  end

end
